name: Check code compilation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install nbdkit-plugin-dev libcurl4-openssl-dev
    - name: Build multi-http-plugin
      run: |
        make
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    - name: Build python libs
      run: |
        ./setup.py build
    - name: Install test dependencies
      run: |
        sudo apt-get -y install nbd-client
        python -m pip install --upgrade pip
        pip install pytest
    - name: Tests
      run: |
        pytest=$(which py.test)
        sudo "PATH=$PATH" $pytest -s -vv tests/
